// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@JavaClass("java.lang.Runtime")
open class Runtime: JavaObject {
  /// Java method `exit`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void java.lang.Runtime.exit(int)
  /// ```
@JavaMethod
  open func exit(_ arg0: Int32)

  /// Java method `runFinalization`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void java.lang.Runtime.runFinalization()
  /// ```
@available(*, deprecated)
  @JavaMethod
  open func runFinalization()

  /// Java method `load`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void java.lang.Runtime.load(java.lang.String)
  /// ```
@JavaMethod
  open func load(_ arg0: String)

  /// Java method `loadLibrary`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void java.lang.Runtime.loadLibrary(java.lang.String)
  /// ```
@JavaMethod
  open func loadLibrary(_ arg0: String)

  /// Java method `gc`.
  ///
  /// ### Java method signature
  /// ```java
  /// public native void java.lang.Runtime.gc()
  /// ```
@JavaMethod
  open func gc()

  /// Java method `availableProcessors`.
  ///
  /// ### Java method signature
  /// ```java
  /// public native int java.lang.Runtime.availableProcessors()
  /// ```
@JavaMethod
  open func availableProcessors() -> Int32

  /// Java method `freeMemory`.
  ///
  /// ### Java method signature
  /// ```java
  /// public native long java.lang.Runtime.freeMemory()
  /// ```
@JavaMethod
  open func freeMemory() -> Int64

  /// Java method `maxMemory`.
  ///
  /// ### Java method signature
  /// ```java
  /// public native long java.lang.Runtime.maxMemory()
  /// ```
@JavaMethod
  open func maxMemory() -> Int64

  /// Java method `halt`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void java.lang.Runtime.halt(int)
  /// ```
@JavaMethod
  open func halt(_ arg0: Int32)

  /// Java method `totalMemory`.
  ///
  /// ### Java method signature
  /// ```java
  /// public native long java.lang.Runtime.totalMemory()
  /// ```
@JavaMethod
  open func totalMemory() -> Int64
}
extension Runtime {
  @JavaClass("java.lang.Runtime$Version")
  open class Version: JavaObject {
    /// Java method `equals`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean java.lang.Runtime$Version.equals(java.lang.Object)
    /// ```
  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

    /// Java method `toString`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String java.lang.Runtime$Version.toString()
    /// ```
  @JavaMethod
  open override func toString() -> String

    /// Java method `hashCode`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.lang.Runtime$Version.hashCode()
    /// ```
  @JavaMethod
  open override func hashCode() -> Int32

    /// Java method `compareTo`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.lang.Runtime$Version.compareTo(java.lang.Runtime$Version)
    /// ```
  @JavaMethod
  open func compareTo(_ arg0: Runtime.Version?) -> Int32

    /// Java method `compareTo`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.lang.Runtime$Version.compareTo(java.lang.Object)
    /// ```
  @JavaMethod
  open func compareTo(_ arg0: JavaObject?) -> Int32

    /// Java method `update`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.lang.Runtime$Version.update()
    /// ```
  @JavaMethod
  open func update() -> Int32

    /// Java method `major`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.lang.Runtime$Version.major()
    /// ```
  @available(*, deprecated)
  @JavaMethod
  open func major() -> Int32

    /// Java method `minor`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.lang.Runtime$Version.minor()
    /// ```
  @available(*, deprecated)
  @JavaMethod
  open func minor() -> Int32

    /// Java method `feature`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.lang.Runtime$Version.feature()
    /// ```
  @JavaMethod
  open func feature() -> Int32

    /// Java method `interim`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.lang.Runtime$Version.interim()
    /// ```
  @JavaMethod
  open func interim() -> Int32

    /// Java method `equalsIgnoreOptional`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean java.lang.Runtime$Version.equalsIgnoreOptional(java.lang.Object)
    /// ```
  @JavaMethod
  open func equalsIgnoreOptional(_ arg0: JavaObject?) -> Bool

    /// Java method `patch`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.lang.Runtime$Version.patch()
    /// ```
  @JavaMethod
  open func patch() -> Int32

    /// Java method `security`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.lang.Runtime$Version.security()
    /// ```
  @available(*, deprecated)
  @JavaMethod
  open func security() -> Int32

    /// Java method `compareToIgnoreOptional`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int java.lang.Runtime$Version.compareToIgnoreOptional(java.lang.Runtime$Version)
    /// ```
  @JavaMethod
  open func compareToIgnoreOptional(_ arg0: Runtime.Version?) -> Int32
  }
}
extension JavaClass<Runtime.Version> {
  /// Java method `parse`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.lang.Runtime$Version java.lang.Runtime$Version.parse(java.lang.String)
  /// ```
@JavaStaticMethod
  public func parse(_ arg0: String) -> Runtime.Version!
}
extension JavaClass<Runtime> {
  /// Java method `getRuntime`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.lang.Runtime java.lang.Runtime.getRuntime()
  /// ```
@JavaStaticMethod
  public func getRuntime() -> Runtime!

  /// Java method `version`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.lang.Runtime$Version java.lang.Runtime.version()
  /// ```
@JavaStaticMethod
  public func version() -> Runtime.Version!
}
